### ISSUE TITLE
Cross-frame problems

### ISSUE THREAD

**Issue by SirPepe** [baconjs/bacon.js#296]
I just noticed that much of Bacon.js won't work across frame borders. Example: http://files.peterkroener.de/baconframes/a.html

The culprits are the assert functions that use `instanceof`, which [doesn't work across browsing contexts](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof#instanceof_and_multiple_context_%28e.g._frames_or_windows%29).

I'm not really sure what a good fix would be. Maybe `toString()` instead of `instanceof`?

**Comment by antris** [comment]
We hit this mine in our codebase. Would it be possible to make a better error message at least? Or better yet, move on to a better compatibility check than `instanceof`?

I don't really understand why this ticket was closed? Due to lack of time?

**Comment by raimohanska** [comment]
Added to FAQ, closed :) Maybe we need something better, @antris. If you've got ideas for better compatibility check, feel free to express them. 

The check could of course be laxed a bit to allow multiple Bacons so to say. But. The internal details related to preventing glitches (duplicate events) depend on hidden global internal state that would then be different in the two Bacon instances. That might lead to some "interesting" effects and right now I don't think it's something we want to start debugging. To make sure stuff works a bunch of new automatic tests would be needed etc.

**Comment by antris** [comment]
For example Bacon tagging all EventStreams it creates with a version number/object and then comparing if the two versions are compatible?

**Comment by raimohanska** [comment]
That won't solve the issue of having two separate instances of internal state.

**Comment by antris** [comment]
If the state problem cannot be fixed within a reasonable workload then how about giving an error message that refers to the FAQ?

**Comment by pozadi** [comment]
Maybe it could help if global state will be created not per instance of the library, but once for all instances? Something like `window._baconState`, or `window['@baconState' + Bacon.version]`.

**Comment by AgentME** [comment]
Making shared state depend on the exact version number could lead to frustrating issues: imagine a project uses libraries A which depends on baconjs:0.7.53 and B which depends on baconjs:^0.7.53. As long as 0.7.53, bacon streams from A and B will interoperate fine, but once Bacon 0.7.54 is released, they'll stop interoperating.

Making shared state not depend on the exact version number restricts how future versions can change the state of course. Both ways of sharing state having problems makes that strategy not seem so great to me.

**Comment by pozadi** [comment]
Hmm, it can be `window['@baconState' + lowestCompatibleVersion]`, but I'm also not a fan of this idea. Just a theoretical suggestion of how it can be solved :)
