### ISSUE TITLE
Property created from Bus skips values

### ISSUE THREAD

**Issue by phadej** [baconjs/bacon.js#304]
``` coffee
"use strict";

Bacon = require "baconjs";

bus = new Bacon.Bus();
busProp = bus.toProperty 1;

bus.push 2

busProp.onValue (v) ->
  console.log "a", v;

busProp.onValue (v) ->
  console.log "b", v;

bus.push 3
```

will output

```
a 1
b 1
a 3
b 3
```

though I would expect

```
a 2
b 2
a 3
b 3
```

Is this by design? I would like to have "settable" Property, for which `bus.toProperty()` otherwise would be enough.

Another example, is with `stream.scan`:

``` coffee
  bus = new Bacon.Bus();
  busProp = bus.scan 1, (a, b) -> a + b

  bus.push 2

  busProp.onValue (v) ->
    console.log "c", v;

  busProp.onValue (v) ->
    console.log "d", v;

  bus.push 3
```

The output is the same.

I think `stream.toProperty` could be still fully lazy (= omitting some calculations at the end) (as long as we use [Applicative](http://hackage.haskell.org/package/base-4.6.0.1/docs/Control-Applicative.html) combinators)

``` coffee
# can just hold the last thunk
busProp = bus.toProperty().map veryExpensiveTransformation

# have to buffer or calculate
busProp = bus.scan 0, notSoExpensiveCombine

# monadic bind ruins laziness as well
busProp = bus.flatMap(someExpandingFunctionAsWell).toProperty();
```

**Comment by timmolendijk** [comment]
> behavior predicated on the existence of a listener? Ewww

I'm very much with @popham here. Isn't this a very clear no-go? In my opinion, being able to make your software decomposable and minimally interdependent is the _raison d'être_ of the functional reactive programming style.

The behavior described in this issue runs counter to this. Blegh.

**Comment by raimohanska** [comment]
Well I don't like this either. This might be one of the things to fix for 0.8, but it does require a special Property implementation for a Bus, as normally a Property is not listening to its source unless it has listeners itself. This is the very mechanism that makes Bacon.js do resource management automatically.

Generally I suggest you guys to avoid Buses altogether as they usually are a design smell.

**Comment by timmolendijk** [comment]
I totally agree that Buses are generally not needed, but I bumped my head very hard against this issue without touching Buses directly. I simply used angular-bacon's `$scope.$watchAsProperty()`, which uses a Bus internally. Would you recommend they change their implementation?

**Comment by raimohanska** [comment]
Well I certainly do I there's a way to avoid Bus. 

I'll also embrace a Pull Requst that'll patch the issue with Bus.toProperty so that it'll always be up to date:)

**Comment by timmolendijk** [comment]
I'm not confident that I fully understand all implications/ramifications that you referred to (regarding resource management), but I will see what I can do.

Thanks for the responsiveness!

**Comment by timmolendijk** [comment]
Upon closer investigation I believe that the issue at hand here is actually a much deeper one, unrelated to `Bus` but rather related to the nature of `Property`. A detailed elaboration can be found in #536, but in the context of this issue, here is @phadej's code sample slightly rewritten to make it behave as expected. Note that we need a feature that allows us to pass a function to `toProperty`, which is currently not possible, so this code sample is purely hypothetic for now.

```coffeescript
i = 1

bus = new Bacon.Bus();
# Making the initial property value evaluate lazily just like the rest of the property
# would allow us to work around the counter-intuitive behavior.
busProp = bus.toProperty -> i;

bus.push ++i

busProp.onValue (v) ->
  console.log "a", v;

busProp.onValue (v) ->
  console.log "b", v;

bus.push ++i
```

The alternative, more profound, solution would be to change the way properties behave and strip them from all laziness. Although I think this would make sense (see #536) I do understand that this is a massive change that impacts all laziness, including in event streams. The solution as proposed in the preceding code sample would be the more pragmatic, short-term way-to-go.
