### ISSUE TITLE
Implement the Fantasy Land Spec?

### ISSUE THREAD

**Issue by mkaemmerer** [baconjs/bacon.js#352]
Bacon could easily be made to implement the Fantasy Land Specification (https://github.com/fantasyland/fantasy-land), which defines a number of interfaces for algebraic structures.

Here's what it would take:

Add ```observable.chain``` as a synonym for ```observable.flatMap```
Add ```Bacon.empty``` as a synonym for ```Bacon.never```
Add ```Bacon.of``` as a synonym for ```Bacon.once```
Add ```observable.ap```

    Observable.ap = x -> this.combine(x, (f,x) -> f x)

To be honest, I don't know how much implementing this spec would help Bacon. On the other hand, Bacon could be instrumental in spreading adoption of Fantasy Land. Thoughts?

**Comment by semmel** [comment]
> The problem is that they (er, @puffnfresh) say that the chain and ap methods should be consistent.

Probably the [condition for deriving ap from chain](https://github.com/fantasyland/fantasy-land/tree/v4.0.1#derivations). 
```
ap(mf, ma) ≡ chain(f => map(f, ma), mf)
```

What still "sort-of" [works for single temporal values from asynchronous computations](https://github.com/fluture-js/Fluture#ap), breaks down for temporal streams of values: `chain` means to merge a higher order stream, and
>  I think the only sane definition of ap would be based on combine.

`ap` and `chain` do no longer fit together for reactive streams.

How bad would it be to "screw that rule" and implement `ap ≅ combine(f => a => f(a))` and `chain ≡ flatMap` ? On could still derive useful functions like `liftA2` from `FL.ap` and `FL.map` etc.

It is certainly useful to have FL "light" compatibility, but is it also too dangerous?
