### ISSUE TITLE
A groupBy operator

### ISSUE THREAD

**Issue by xgrommx** [baconjs/bacon.js#368]
Hello @raimohanska 

In RxJS has an operator like a groupBy. But in BaconJS I can't found approach how can I do it. Maybe you can to help with it problem because it an operator is very useful as for me.

**Comment by raimohanska** [comment]
This would be nice, but I don't have the time. Who turns up with a groupBy impl?

**Comment by alexandrelan** [comment]
Hi @raimohanska,

I was going to give it a try, but I saw .groupBy() was already implemented.
Can this issue be closed, or does it stay anything to implements ?

**Comment by raimohanska** [comment]
Good point :) i guess this one was simply forgotten.
