### ISSUE TITLE
An index in a map or similar functions.

### ISSUE THREAD

**Issue by xgrommx** [baconjs/bacon.js#369]
Hello @raimohanska 

I have some improvement with an index in map or similar functions. That is will be very useful and excluding side effect with another variable for an index of element.

For example:
Now I should do it so:

``` js
var index = 0;
Bacon.fromArray([1,2,3,4,5]).map(x -> ({ value: x, index: index++ })).log();
```

If will be an index in map function it will be very simple and without side effects use it:

``` js
Bacon.fromArray([1,2,3,4,5]).map((x, index) -> ({ value: x, index: index })).log();
```

**Comment by gnapse** [comment]
RxJS' map, flatMap pass the index to the mapping function, as the second parameter. Is there any reason Bacon.js doesn't/can't do it?
