### ISSUE TITLE
Update Bacon.js on baconjs.github.io

### ISSUE THREAD

**Issue by BlackYoup** [baconjs/bacon.js#460]
It seems that the 0.7.28 version broke some stuff, but it's the version used on your website at http://baconjs.github.io/

Could you update it ? I enjoy trying Bacon on this page but some functions that use "timers" (e.g. sequentially) are broken :(

Thanks :)

**Comment by phadej** [comment]
Resolved in https://github.com/baconjs/baconjs.github.io/commit/d5bfb9168d270f05fd597437183be972ecba3cc9

![screen shot 2015-01-07 at 11 48 58](https://cloud.githubusercontent.com/assets/51087/5643612/4553dcd2-9663-11e4-8b9c-79b058c47e1d.png)

**Comment by BlackYoup** [comment]
Thanks !
