### ISSUE TITLE
Lazy evaluation: good or bad?

### ISSUE THREAD

**Issue by raimohanska** [baconjs/bacon.js#465]
The fact that bacon.js evaluates event values lazily is a bit confusing. This bit me in my Oredev presentation. So if I couldn't take that into account, how many new Bacon.js users will?

Now, if you do

``` javascript
    fieldValue = $(".foo").asEventStream('keyup').map((e) => $(e.currentTarget).val()).toProperty()
    firstClick = clicks.take(1)
    secondClick = clicks.skip(1).take(2)
    twoValues = Bacon.combineAsArray(
      fieldValue.sampledBy(firstClick),
      fieldValue.sampledBy(secondClick)
    )
    twoValues.log()
```

What do you get? An array of the values of the `.foo` textfield at the times of first and second click? Well, not exactly. You'll get the value of the textfield at the time of the second click, twice.

This is because the value of the events isn't evaluated until it's actually used. (see also https://github.com/baconjs/bacon.js/#lazy-evaluation)

Now the question is, should we remove lazy evaluation altogether in Bacon.js 0.8? My suggestion would be to make a spike and see if that brings any serious performance penalty. Then proceed accordingly.

**Comment by philipnilsson** [comment]
I disagree with removing lazy evaluation on the basis it "might be
confusing". In my opinion the correct way to use Bacon.js is to use it as a
library that provides event streams that are pure values with semantics
specified at the time of constructing them. Code such as
stream.map(getSomethingStateful()) do not follow this principle, and can be
written someStream.sampledBy(stream).

After all we interact w/ steams by subscribing, not by doing .map(effect).
For consistency, we should then provide an analogue to the doAction
combinator, maybe something like stream.pick(function() { $('input').val();
})

I don't think I'll ever agree there are any semantic benefits to removing
lazy eval. If there are performance concerns I'd like to see a significant
difference in a real world application (where strict wins). If this is true
I'm perfectly fine with getting rid of it.

**Comment by raimohanska** [comment]
I'm still not 100% sure whether is a go or a no-go for 0.8... I'm leaning on the go-side though.

**Comment by raimohanska** [comment]
Lazy eval will be removed in 2.0.
