### ISSUE TITLE
Streams dispose logic

### ISSUE THREAD

**Issue by gyzerok** [baconjs/bacon.js#481]
For example i'm using bacon with socket.io like this:

```javascript
var conns = Bacon.fromBinder(function (sink) {
    io.on('connect', sink);
});
```

Suppose there is no other streams referring ```conns```. What would happen if now clear ```conns```?

```javascript
conns = null;
```

Would all the resources be correctly cleared?
And what about anonymous streams? How to determine their lifetime? For example: 

```javascript
Bacon.combineAsArray(conns, property)
      .onValues(function (socket, property) {
             console.log(socket, property);
      });
```

**Comment by raimohanska** [comment]
Fixed along with #506
