### ISSUE TITLE
combine ends only when both of its inputs end

### ISSUE THREAD

**Issue by renarl** [baconjs/bacon.js#495]
The documentation (https://github.com/baconjs/bacon.js/wiki/Diagrams#combine) states that a combined stream should end when _either_ of its inputs ends. But in the following example, when bus `a` ends, the combined stream `c` does not end. 
```javascript
a = new Bacon.Bus().log('a')
b = new Bacon.Bus().log('b')
c = a.combine(b, function(a, b) {return [a, b];}).log('c')

c.onEnd(function(){console.log('c end')})

a.end()
```
The `c` ends only after the stream `b` ends.

**Comment by AgentME** [comment]
I think this should be seen as a bug with the documentation. If the combined stream ended when either of the inputs ended, then you wouldn't be able to combine ended properties (such as returned by `Bacon.constant(x)`) with other things.

**Comment by raimohanska** [comment]
Fixed the description. Like it now?

**Comment by renarl** [comment]
In that case, is there an alternative method that behaves like combine but ends when _either_ of its inputs ends?

**Comment by raimohanska** [comment]
You'll have to roll you own :)
