### ISSUE TITLE
fromEventTarget does not work with socket.io Server events

### ISSUE THREAD

**Issue by chreekat** [baconjs/bacon.js#506]
The Server object contains both a `bind` and an `on` method, and `fromEventTarget` erroneously uses `bind`.

http://socket.io/docs/server-api/#server#bind(srv:engine#server):server

**Comment by raimohanska** [comment]
Well that should be an easy fix, right? Just change the ordering in fromEventTarget?

**Comment by chreekat** [comment]
Is it? :) Would that break the method for some other 3rd party library? I don't actually know.

**Comment by raimohanska** [comment]
Good point :) 

A better approach might be to check for the existence of the pairs `[["addEventListener","removeEventListener"], ["addListener", "removeListener"], ["on", "off"], ["bind", "unbind"]]` to prevent accidental matches.

**Comment by raimohanska** [comment]
The fix's in master now. Care to try it before we release? I need sleep now, though :)

**Comment by chreekat** [comment]
Sadly I merely discovered this through trying to answer a [SO question](https://stackoverflow.com/questions/27680475/failed-to-convert-socket-io-event-to-bacon-eventstream) :P  Maybe ping the questioner?

**Comment by chreekat** [comment]
Clever fix, by the way. :)

**Comment by raimohanska** [comment]
0.7.46 is out, pls try again!
