### ISSUE TITLE
flatMapError

### ISSUE THREAD

**Issue by phadej** [baconjs/bacon.js#508]
We have
- `observable.map(@ : Observable[A], f : A -> B) : Observable[B]`
- `observable.flatMap(@ : Observable[A], f : A -> Observable[B] | Event[B] | B) : EventStream[B]`
- `observable.mapError(@ : Observable[A], f : E -> A) : Observable[A]`

Should we have

``` js
observable.flatMapError(@ : Observable[A], f : E -> Observable[A] | Event[A] | A) : EventStream[A]
```

for completeness?

_Extra:_ how about
- `observable.eventMap(@ : Observable[A], f : E -> Array[Event[B] | B] | Event[B] | B) : Observable[B]`
- `observable.eventMapError(@ : Observable[A], f : E -> Array[Event[A] | A] | Event[A] | A) : EventStream[A]`
  with or without `Array magic`.

`eventMap` would be generalisation of `filter` and  `eventMapError` is usable when you want to recover only from some errors.

``` js
stream
  .map(function (x) {
    return [x, x];
  })
  .flatMap(Bacon.fromArray)
// or
stream.eventMap(function (x) {
  return [x, x];
});
```

**Comment by raimohanska** [comment]
The `flatMapError` method has been around since version 0.7.12 so closing the issue.
