### ISSUE TITLE
We hardly new ya

### ISSUE THREAD

**Issue by AlexGalays** [baconjs/bacon.js#510]
It would be convenient to make it optional to 'new' the various types used in Bacon:  Bacon.Bus, Bacon.Next, etc.

The following technique can be used: 

```
function Bus() {
    if (!(this instanceof Bus)) {
        return new Bus();
    }
}
```

I get that prototypical inheritance is used for performances/memory, but seeing these 'new' operators again is an eye sore and is easy to forget.

**Comment by raimohanska** [comment]
Well I'm actually in favor for this. Sorry for ignoring. Too busy :) A PR might get this though.

**Comment by raimohanska** [comment]
This has been implemented quite a long time ago already :)
