### ISSUE TITLE
Project source is one 1800 line file?

### ISSUE THREAD

**Issue by Marak** [baconjs/bacon.js#512]
I was interested in checking out this project, but the majority of the source code seems to exist in one monolithic file `bacon.coffee` found [here](https://github.com/baconjs/bacon.js/blob/master/src/Bacon.coffee)

Maybe I missed something? Is there another place to find the source code broken down into separate files?

**Comment by raimohanska** [comment]
Yes, the whole thing is in Bacon.coffee :) Not a desirable design, of course. There's been discussion about splitting into modules and also porting to ES6. If you're interested in helping in these effort you're welcome! Join the chat: https://gitter.im/baconjs/bacon.js

**Comment by Marak** [comment]
More interested in reading the source than contributing at this time. Please update this issue if you split the source into separate files. Thanks!

**Comment by eguneys** [comment]
What does it take to understand the source code, It seems easy enough, though I studied monads for a week and then gave up.

**Comment by raimohanska** [comment]
@eguneys I didn't get your point...

**Comment by raimohanska** [comment]
Well, it's now split into pieces!
