### ISSUE TITLE
Merging synchronous stream with self doesn't work right

### ISSUE THREAD

**Issue by AgentME** [baconjs/bacon.js#520]
This should print out 2, 3, and \<end\>, but only 2 and \<end\> get printed.

```javascript
var Bacon = require('baconjs');

var s = Bacon.once(2);
s.merge(s.map(3).delay(1)).log();
```

Changing it to be `var s = Bacon.once(2).delay(1);` or merging against a different stream like `s.merge(Bacon.once(2).map(3).delay(1)).log();` both work fine.

Bacon 0.7.41 from NPM

**Comment by raimohanska** [comment]
Known issue, sorry :( See #367
