### ISSUE TITLE
`Bacon.noMore` doesn't work with `Bacon.once(1).merge(Bacon.interval(100, 2))`

### ISSUE THREAD

**Issue by pozadi** [baconjs/bacon.js#523]
Not sure if I found a bug, or doing something wrong myself. 

Following example doesn't work correctly. If ran in node it prints `1` but the node process doesn't terminates, which probably means that `Bacon.interval(100, 2)` still working.

```
Bacon = require('baconjs');

Bacon.once(1).merge(Bacon.interval(100, 2)).subscribe(function(event) {
  console.log(event);
  return Bacon.noMore;
});
```

If we take two events everything works just fine:

```
Bacon = require('baconjs');

var count = 0;
Bacon.once(1).merge(Bacon.interval(100, 2)).subscribe(function(event) {
  console.log(event);
  return count++ === 1 ? Bacon.noMore : Bacon.more;
});
```

**Comment by raimohanska** [comment]
Thanks @pozadi, a good find! Easily fixable too.

**Comment by pozadi** [comment]
Thanks :+1:
