### ISSUE TITLE
onError is not called if onValue is called first

### ISSUE THREAD

**Issue by eguneys** [baconjs/bacon.js#528]
This logs the error fine.
```js
var onceerr = Bacon.once(new Bacon.Error({}));
//onceerr.onValue(function(v) { console.log(v); });
onceerr.onError(function(v) { console.log(v); });
```
If you remove the comment nothing is printed.

**Comment by phadej** [comment]
This is known "issue". When you attach `onValue` -handler, the events are drained from `onceerr`. So at the (time) point, when you attach `onError`, the stream is already empty. You can circumvent the issue by using [`subscribe`](http://baconjs.github.io/api.html#stream-subscribe).

**Comment by eguneys** [comment]
I am using this helper function to listen to all three events now:

```js
subscribeStream = function(stream, handlers) {
  stream.subscribe(function(e) {
    if (e.isNext() && handlers.onValue) {
      handlers.onValue(e.value());
    }
    else if (e.isEnd() && handlers.onEnd) {
      handlers.onEnd(e);
    }
    else if (handlers.onError) {
      handlers.onError(e.error);
    }
  });
};
```

**Comment by AgentME** [comment]
@eguneys You should use `e.hasValue()` instead of `e.isNext()`, or else initial events such as from properties will be treated as errors.

**Comment by raimohanska** [comment]
In the `0.8` branch, both `once` and `fromArray` are asynchronous, so this problem won't happen again.

**Comment by raimohanska** [comment]
This is a duplicate to #367 -> closing
