### ISSUE TITLE
Document Property behaviour after end

### ISSUE THREAD

**Issue by XeCycle** [baconjs/bacon.js#532]
As I see now a property still holds the last value after it ended, but found its documentation nowhere in the docs or tests.  My program now relies on this behavior, can we have it documented and tested?

It is like,
```
Promise.resolve(Bacon.never().toProperty(1)).then(function(stream){stream.onValue(console.log)})
```
I expect 1 to show up in the console.

**Comment by raimohanska** [comment]
It's expected and tested behavior. Doc update makes sense. Wanna PR?

-juha-
