### ISSUE TITLE
support arrays in property extractor

### ISSUE THREAD

**Issue by chrylis** [baconjs/bacon.js#534]
I'm trying to map the value of a file input, and the `files` property is an array. I can specify `map(".target.files")` on my observable, but `map(.target.files[0])` is `undefined`. It would be helpful to be able to include indices in the extractor expression.

**Comment by wolfflow** [comment]
It's possible with 
```js
Bacon.once({targets:["foo"]}).map(".targets.0").log()
```

**Comment by chrylis** [comment]
This works perfectly but is surprising. Could you make a note on the documentation for the property-extractor syntax?

**Comment by wolfflow** [comment]
Notes are already there: https://github.com/baconjs/bacon.js#function-construction-rules

`stream.map(".dudes.1")` would pick the second object from the nested "dudes" array. For example, you'd get "jack" for `{ dudes : ["john", "jack"] }`.

**Comment by raimohanska** [comment]
thanks @wolfflow you were faster this time :)

**Comment by chrylis** [comment]
I read that but didn't connect the property extractor and the function-construction rules. I think I'm starting to get the idea; thanks for the help.

**Comment by raimohanska** [comment]
Should we improve documentation on that part? The term "function construction rules" may be a bit strange; it's just something I came up with, and I'm not a native English speaker...

**Comment by chrylis** [comment]
I don't know. It's a little unclear, but I'm new to serious JavaScript (I've been avoiding it for 15 years), and I'm still uncomfortable with its weird mashup of functional and procedural styles. It may just be the best description of a complicated concept. I'm willing to help revise some of the documentation (including perhaps clearing up some difficult areas for people new to the concepts); reworking our new Web utility with Bacon has made the code clearer to read and more reliable, and I'd like to both understand it better and make it available to a broader audience.
