### ISSUE TITLE
Promise support in maps

### ISSUE THREAD

**Issue by chrylis** [baconjs/bacon.js#535]
I have a library function that does some async image manipulation and returns a Promise. As far as I can tell, the only way for me to embed the Promise in my chain is to wrap it in a function that calls `Bacon.fromPromise`; there's no other way to get the parameter to the library function call:

    .flatMapLatest(function(val) { return Bacon.fromPromise(libraryFunction(val)); })

It would be helpful to have a combined `fromPromise` wrapper call so that instead I could write:

    .flatMapLatestFromPromise(libraryFunction)

(Not sure whether the `FromPromise` would be necessary here, but it would be cleaner than the existing syntax.)

**Comment by mkaemmerer** [comment]
How about ```stream.map(libraryFunction).flatMapLatest(Bacon.fromPromise)```?

Whenever you see yourself needing a combinator that does two things (like flatMapLatestFromPromise), it's a good sign that you should look for a way to do it as a composition of two different combinators.

**Comment by chrylis** [comment]
And that does it. I'm still pretty new to reactive programming, and JavaScript isn't my native language, so I overlooked that composition route. Still getting my head around some of the JS function idioms.
