### ISSUE TITLE
0.7.44 throws exception when using .bufferWithTime

### ISSUE THREAD

**Issue by shcarrico** [baconjs/bacon.js#545]
will update with more details..

**Comment by raimohanska** [comment]
please do!

**Comment by shcarrico** [comment]
`Bacon.scheduler.clearTimeout`, `clearTimeout` is undefined within buffer.flush

**Comment by shcarrico** [comment]
https://github.com/baconjs/bacon.js/blob/master/dist/Bacon.js#L2139

**Comment by shcarrico** [comment]
sorry, would do up a test etc.. but wanted to raise flag :3

**Comment by raimohanska** [comment]
np, my bad, will fix. thanks for the timely report!

**Comment by raimohanska** [comment]
The problem is that in the tests, the scheduler is replaced with a mock to improve speed and reliability. I added the missing method and released 0.7.45.

**Comment by raimohanska** [comment]
I hope this helps!

**Comment by shcarrico** [comment]
works now.. thank you very much sir.

**Comment by raimohanska** [comment]
thank you too. always embarrassing to release foobar versions, so your speedy reporting is highly appreciated!
