### ISSUE TITLE
takeUntil does not stop listening on synchronously-emitting stream

### ISSUE THREAD

**Issue by AgentME** [baconjs/bacon.js#546]
``` javascript
var Bacon = require('baconjs');

function makeStream() {
  return Bacon.fromBinder(function(sink) {
    console.log('subbed');
    sink(1);
    return function() {
      console.log('unsubbed');
    };
  });
}

var stream = Bacon.later(50, 'beep');

stream.takeUntil(makeStream()).log('::stream::');
```

The output is:

```
subbed
::stream:: <end>
```

"unsubbed" should be in there somewhere.

**Comment by raimohanska** [comment]
Indeed I think there's a bug going on. Synchronous streams never fail to provide new cases. I made a fix in the fix/546 branch, but there's no test yet.

**Comment by raimohanska** [comment]
I guess the relevant case would be synchronous endless stopper stream, but that still fails as shown in 7cc0b7b

Gotta say this is not a very typical use case. Not sure if it makes sense to go deeper here. I'll take the first fix to master anyway.

**Comment by AgentME** [comment]
Would `takeUntil` calling `take(1)` on its stopper stream fix that?

**Comment by raimohanska** [comment]
Maybe? Wanna try an pr?

**Comment by raimohanska** [comment]
Well it seems so. I think we could simplify and make `takeUntil` more efficient by a more direct implementation.

**Comment by raimohanska** [comment]
In 2.0, there will be no synchrnously emitting streams.
