### ISSUE TITLE
error in combine promise streams

### ISSUE THREAD

**Issue by 21paradox** [baconjs/bacon.js#550]
'not a function or a field key: undefined' error throwing while combine promise streams.

merge method is working fine.

reproduced here: http://jsbin.com/fuveje/2/edit

One more question, when to use merge and when to use combine?

**Comment by raimohanska** [comment]
fromPromise returns EventStream with has no method `combine`. Call stream.toProperty().combine and it'll work just fine.

Merge is used to merge events from 2 sources serially, while combine is used to combine latest values from two sources into one.

**Comment by raimohanska** [comment]
Maybe it would be a good idea to include .combine in EventStream too indeed.

**Comment by 21paradox** [comment]
Got it,  i will add a toProperty method.
Thanks!

**Comment by 21paradox** [comment]
@raimohanska 
I have another question:

Is there a short hand method for simplly combine two property ?
I just want to observe when two property are ready. It can be done by using 'combine' method, but i have to write a pass through function like below.
```javascript
Bacon.fromPromise(ajax_promise)
    .toProperty()
    //use combine to merge two property
    .combine(checkb, function(a, b){
     // can get a,b
     // but have to write return [a, b] passthrough
      return [a, b];
    })

```

jsbin: http://jsbin.com/fuveje/5/edit?html,js,console

**Comment by raimohanska** [comment]
Try Bacon.combineAsArray, see readme

-juha-

**Comment by 21paradox** [comment]
solved! thanks.
