### ISSUE TITLE
Migrating to ES6.

### ISSUE THREAD

**Issue by phadej** [baconjs/bacon.js#553]
Migrating to ES6 is *good thing™* to do in the long run. However mixing CoffeeScript and EcmaScript live together without any restrictions is hard. CoffeeScript transpiler does allocate fresh variables, so we can't transpile Bacon.js parts one-by-one.

---

I shortly tried to serialise [JS-AST to CoffeeScript](https://gist.github.com/phadej/bc422cfd9e3b0187ad3d), but it feels very fragile:

```js
_ = {
  head(xs) {
    return xs[0];
  },
  always(x) { () => x },
}
```
to
```coffee
_ = {head: ((xs) -> (undefined; return xs[0];)), always: ((x) -> (undefined; (() -> (undefined; return x;));))};
```
to
```js
var _;

_ = {
  head: (function(xs) {
    void 0;
    return xs[0];
  }),
  always: (function(x) {
    void 0;
    return function() {
      void 0;
      return x;
    };
  })
};
```

And yes we really need that `undefined` to write CoffeeScript in one line :(

This approach **won't work**.

---

So **I propose** we start with migrating parts that are at the end of the linearised dependency graph:

```
  ... 
  startwith        ← scan, concat, once
  takewhile        ← observable, filter
  throttle         ← buffer, scheduled, map
  update           ← when, scan
  zip              ← _, core, when
  main             ← awaiting, boolean, buffer, bufferingthrottle, bus, callback, combine, concat, core, debounce, diff, doaction, endonerror, errors, factories, frompromise, flatmap, flatmapconcat, flatmaperror, flatmaplatest, flatmapwithconcurrencylimit, fold, holdwhen, jquery, log, maperror, mapend, merge, once, retry, sample, scan, scheduled, skip, skipduplicates, skiperrors, skipuntil, skipwhile, slidingwindow, spy, startwith, take, takewhile, takeuntil, throttle, update, when, zip
```

So we will have some coffeescript followed by ecmascript 6, not intermixed. That approach will work.

**Comment by raimohanska** [comment]
Sounds sound. Here we go!
