### ISSUE TITLE
Grunt, shell scripts, custom JS and coffee scripts.

### ISSUE THREAD

**Issue by phadej** [baconjs/bacon.js#556]
Lately while making es6 setup I noticed that build stuff is too complicated.

We have:
- Gruntfile: which does almost nothing
- Custom scripts, because we have custom steps
- Shell scripts wrappers around both

I'd like to simplify the system, by either:
- Using grunt-shell in grunt (to get rid of shell scripts) (_-0.1_)
- Use `[make](http://www.gnu.org/software/make/)` to get rid of shell scripts and grunt (_+1_)
  - And windows support is not good ATM anyway, because of shell scripts

**Comment by raimohanska** [comment]
In version 2.0 the build is simpler: no more grunt. Everything is run using `npm` scripts
