### ISSUE TITLE
Typo in tutorial

### ISSUE THREAD

**Issue by JonathanHayward** [baconjs/bacon.js#558]
I'm sorry for posting this as an issue rather than a pull request; I couldn't see where to fork / edit / generate pull request.

On the tutorial, we have:

> This relies on **te** fact that the onValue method, like many other Bacon.js methods, supports different sets of parameters. On of them is the above form, which can be translated as "call the attr method of the register button and use disabled as the first argument". The second argument for the attr method will be taken from the current property value.

This is probably meant with an H, as:

> This relies on **the** fact that the onValue method, like many other Bacon.js methods, supports different sets of parameters. On of them is the above form, which can be translated as "call the attr method of the register button and use disabled as the first argument". The second argument for the attr method will be taken from the current property value.

**Comment by frankcash** [comment]
@JonathanHayward you would do this on the [Github Page](https://github.com/baconjs/baconjs.github.io/search?utf8=✓&q=This+relies+on+te+fact) repository for Bacon.js.
