### ISSUE TITLE
skipWhile documentation misleading

### ISSUE THREAD

**Issue by AgentME** [baconjs/bacon.js#559]
skipWhile's documentation doesn't mention that it does not resume skipping if the function or property holds true again.

>stream.skipWhile(f) skips elements while given predicate function holds true. The Function Construction rules below apply here.
>stream.skipWhile(property) skips elements while the value of the given Property is true.

From reading this, my expectation was that it would work more like `filter` (but interpreting true and false oppositely) than `takeUntil`.

**Comment by raimohanska** [comment]
Agreed it could be better. Wanna PR?

-juha-
