### ISSUE TITLE
cannot access sideshow with touch.

### ISSUE THREAD

**Issue by SteveALee** [baconjs/bacon.js#577]
Slide show is inaccessible on touch device as no touch UI. I was using Firefox on Android.

**Comment by raimohanska** [comment]
that's, err, some really old slideset indeed. maybe we should just remove it...

**Comment by SteveALee** [comment]
heh.
Are there any other beginners resources that could be added to Getting Started at http://baconjs.github.io/?

I was coming from https://gist.github.com/staltz/868e7e9bc2a7b8c1f754 and Parikka's bacon fork : http://jsfiddle.net/paprikka/dmgnhmxo/3/

**Comment by SteveALee** [comment]
Running through the slide show now have keyboard the live demos are nice - though don't all work.
Also made it clear jQuery is a dependency wich as a complete newbie I hadn't grokked

**Comment by raimohanska** [comment]
Oh take it easy, jQuery is not a dependency :)
