### ISSUE TITLE
Element ref in onValue function

### ISSUE THREAD

**Issue by laveesht** [baconjs/bacon.js#579]
Is there a better way to get element ref inside onValue() of any property or stream.

someSteam/property.onValue(function(value){
$(event.srcElement) // other than this
})

**Comment by raimohanska** [comment]
Well, that's about it. If the element is what you care about, you might do

    var elementStream = stream.map(function(event) { return $(event.srcElement) })

And then place your subscribers on top of that.

**Comment by jackjennings** [comment]
Slightly related question: Is there a better way to do something like this? I'm not sure if this is as concise/functional as it could be, or if I'm still thinking in an imperative way about the problem.

```es6
var elementStream = stream.map(function(event) { return $(event.srcElement) });
var elementHeight = elementStream.map('.height').map(function(val) { return val + 10 });

elementStream.zip(elementHeight).onValue(function(data) {
  var [element, height] = data;
  element.css({height: height});
}
```

There are a couple of places in my current codebase that I want to compute a value and then use that value to assign something back to the original event target. Is there a way to do this without zip? I particularly don't like having to clump the data together into a temporary array just to get both values… any advice?

**Comment by raimohanska** [comment]
You can use zip of course, but If you don't really need elementHeight as an eventstream, you might just

```
var elementStream = stream.map(function(event) { return $(event.srcElement) });
function elementHeight(el) { return el.height + 10 }

elementStream.onValue(function(el) {
  element.css({height: elementHeight(element)});
}
```

So in this particular case it doesn't really make sense to represent elementHeight as a stream.

Keep it simple :)
