### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by xgrommx** [baconjs/bacon.js#580]
Hello @raimohanska, I got this error

```Uncaught RangeError: Maximum call stack size exceeded```

The code which I use:

```js
var items = _.range(100000);
var double = function(v) { return v * v };
Bacon.fromArray(items).map(double).onValue(function(v) {});
```

**Comment by raimohanska** [comment]
One more problem related to the synchronous nature of `fromArray`. The method turned recursive in commit fed7c8bcd02f297c041f34c46c110daba0d0a696 that fixed #491. I cannot see an elegant fix at the moment.

**Comment by johannhof** [comment]
You could introduce a setTimeout to clear the call stack. Is that too inelegant?

**Comment by raimohanska** [comment]
That would break some tests and would be ugly.

**Comment by raimohanska** [comment]
I came up with a solution which is ugly but doesn't break any tests :)

**Comment by raimohanska** [comment]
Break recursion with a couple of flags. I really hate to do that but I hate changing existing behavior *more* so I guess we'll do this.

**Comment by raimohanska** [comment]
Releasing 0.7.53 with the fix.

**Comment by raimohanska** [comment]
Something went wrong with the release:( Will try again with 0.7.54
