### ISSUE TITLE
Bower.json

### ISSUE THREAD

**Issue by nchaulet** [baconjs/bacon.js#582]
There is an issue in your bower.json l:4 missing coma

**Comment by raimohanska** [comment]
Oops. Is there a way to automagically verify bower.json? Would like to include this into the release script or tests.

This particular problem is fixed in version 0.7.58

**Comment by raimohanska** [comment]
Added test for bower.json validity in 4839d86f3f88427cff931a2004c0bf9fdf4c65f7, 633edc694aafa09aa2575e74eb07b1c48acf9e0c
