### ISSUE TITLE
Unexpected behaviour with combineWith inside map function

### ISSUE THREAD

**Issue by metrip** [baconjs/bacon.js#586]
Reduced test case, working as expected:

``` javascript
var bus = new Bacon.Bus();
var mapped = bus.map(mapFn);

function mapFn(value) {
  console.log('mapFn', value);
  Bacon.combineWith(function() { return 42; });
  return value;
}

mapped.log('mapped-1').log('mapped-2').log('mapped-3');

bus.push(123);
```

output:

```
mapFn 123
mapped-1 123
mapped-2 123
mapped-3 123
```

However, attaching a subscriber to the result of `combineWith` causes the map function to be run as many times as `mapped` has subscribers:

``` javascript
var bus = new Bacon.Bus();
var mapped = bus.map(mapFn);

function mapFn(value) {
  console.log('mapFn', value);
  Bacon.combineWith(function() { return 42; }).log('combined');
  return value;
}

mapped.log('mapped-1').log('mapped-2').log('mapped-3');

bus.push(123);
```

output:

```
mapFn 123
mapFn 123
mapFn 123
combined 42
combined 42
combined 42
combined <end>
mapped-3 123
combined <end>
mapped-2 123
combined <end>
mapped-1 123
```

This seems very unexpected - is this a bug in Bacon?

**Comment by raimohanska** [comment]
Well, that's certainly an unexpected use case. Doesnt seem like a good idea to create new streams inside map, which is supposed to be used with pure functions. You shouldnt rely on the map func to be called exactly once, as that is not a part of its spec. Otoh, this is an unexpected side-effect too. Should be looked into in detail sometime soon.
