### ISSUE TITLE
combineTemplate uses last property value when resubscribing

### ISSUE THREAD

**Issue by dallonf** [baconjs/bacon.js#590]
I've managed to stumble on some peculiar behavior in BaconJS. I'm not sure exactly how to describe it, but I've come up with a code sample which reproduces it, which is almost as good, right? :smile: 

```js
var stream = new Bacon.Bus();
var propBus = new Bacon.Bus();
var property = propBus.toProperty("test1").skipDuplicates();

// "Property changed to test1" - all is well
property.onValue(function (val) {
  return console.log("Property changed to " + val);
});

var combination = Bacon
  .combineTemplate({
    stream: stream.toProperty(null),
    property: property
  });

// "First take: Property via stream is test1" - still fine
combination.take(1).onValue(function (combo) {
  var property = combo.property;
  console.log("First take: Property via stream is " + property);
});

// "Property changed to test2" from first onValue() - as expected
propBus.push("test2");

// "Second take: Property via stream is test1" - This should be "test2", shouldn't it?
combination.take(1).onValue(function (combo) {
  var property = combo.property;
  console.log("Second take: Property via stream is " + property);
});
```

[JSBin here](http://jsbin.com/gibotitola/2/edit)

It seems that when resubscribing to the `combination` property, the old value of "property" is used. Curiously, if you comment out the `stream: stream.toProperty(null),` line, it works as expected.

Feel free to rename this issue if you can think of a good way to describe it!

**Comment by raimohanska** [comment]
This is the classic "why isn't my property updated" from FAQ. The `combination`property is not updated when it has no listeners.

**Comment by dallonf** [comment]
Shouldn't it use the latest value of `property`, though, when it gets a new subscriber?

**Comment by raimohanska** [comment]
It could and it this particular case might be patched to do so, but you still shouldn't rely on properties being updated while not having subscribers. In general, Properties and EventStreams as well do not listen to upstream changes without subscribers and mustn't do so.

**Comment by raimohanska** [comment]
But it's perfectly ok to ask and discuss this, of course!
