### ISSUE TITLE
holdWhen breaks with extended Array.prototype 

### ISSUE THREAD

**Issue by estrato** [baconjs/bacon.js#594]
Example with bacon 0.7.60: http://codepen.io/estrato/pen/NqdKKe

What seems to happen is that Stream.holdWhen() calls _.each() to iterate over buffered values. 
Function _.each() uses "for..in" to iterate over arrays, which means that any properties added to Array.prototype will be iterated over, too.

Some very useful 3rd party libs extend Array.prototype, so it would be cool if holdWhen() used a safer way to iterate over its buffered values.

**Comment by raimohanska** [comment]
Thanks for the find! I added an extra property in Array.prototype for all tests and fixed Bacon._.each.

Fix included in 0.7.64.
