### ISSUE TITLE
Backward incompatible change to EventStream constructor arguments in 0.7.61

### ISSUE THREAD

**Issue by IllusionMH** [baconjs/bacon.js#600]
As I can see ```Bacon.EventStream``` constructor has backward incompatible change to arguments list, but only build number was increased. Also there are no info on API page.
This causes error
```
Uncaught Error: not a function : undefined       Bacon.js:34
assert @ Bacon.js:34
assertFunction @ Bacon.js:57
EventStream @ Bacon.js:1328
...
```

Is it possible to update API docs page and probably minor version number to indicate this  backward incompatible change?

Best regards,
Andrii.

P.S. As solution we started to use ```Bacon.Desc.empty``` as first argument for ```Bacon.EventStream``` constructor.

**Comment by raimohanska** [comment]
Hi, I removed the legacy arg support from the ctor. Sorry for the inconveniece. The Bacon.fromBinder is the documented way to create custom streams.

**Comment by raimohanska** [comment]
The motivation is to simplify and improve performance.

**Comment by wolfflow** [comment]
I've never used ctor for event stream creation myself, though some of third-party bacon plugins might be broken, e.g. backbone.eventstreams by @pyykkis

**Comment by IllusionMH** [comment]
@raimohanska, thanks for the info - I'll y to refactor or code.
But I think that jump to 0.8.0 will avoid some problems with versions like "^0.7.52" asked in npm (not sure about Bower).

**Comment by raimohanska** [comment]
I think I've been too shy to bump minor version.

**Comment by raimohanska** [comment]
I restored the legacy constructor in EventStrean, version 0.7.63.

**Comment by IllusionMH** [comment]
@raimohanska nice. Thanks!
