### ISSUE TITLE
 getPreventDefault() is deprecated.  Use defaultPrevented

### ISSUE THREAD

**Issue by raould** [baconjs/bacon.js#602]
clueless newbie here.

Ubuntu 14.04 x86 / Firefox 38.0 / npm installed Bacon 0.7.65 just now,

I always get the warning "Use of getPreventDefault() is deprecated.  Use defaultPrevented instead."

`<html>
  <head>
    <script type="text/javascript" src="index/Bacon.min.js"></script>
  </head>
  <body>
  </body>
</html>`

**Comment by raimohanska** [comment]
Bacon.js does not use `getPreventDefault`. I don't think this is Bacon.js related. Can you narrow it down to somethint more specific.

**Comment by raould** [comment]
ok, sorry for the noise. probably due to me trying to use some version of jquery?
