### ISSUE TITLE
`observable.filter` with a constant value should filter on the value

### ISSUE THREAD

**Issue by lvanengelen** [baconjs/bacon.js#604]
I expected `filter` to compare with the value when passed a constant, e.g. `.filter("foo")` would match all events with value "foo". Instead it includes everything when the constant is truthy and nothing if it is falsy.

The docs say the following:

> observable.filter(f) filters values using given predicate function. Instead of a function,
> you can use a constant value (true to include all, false to exclude all) [...]

I interpreted this as constant `true` includes all, `false` excludes all, any other constant would filter against the value of the constant.

As an alternative to changing the code, the line from the docs could be changed to something like _"truthy to include all, falsy to exclude all"_

**Comment by raimohanska** [comment]
Check out Bacon.matchers lib for this functionality.

And yes we could clarify! Want to PR?

-juha-

**Comment by lvanengelen** [comment]
Ah, thanks for the pointer to Bacon.matchers. I overlooked that one :)

With PR you mean a pull request? I think I can whip something up .

**Comment by raimohanska** [comment]
Yup, a PR. You might even include a link to Bacon.Matchers. Pls check the Contributing section on readme 1st to avoid typical errors :) Thanks!
