### ISSUE TITLE
Strange behaviour with holdWhen and getValue

### ISSUE THREAD

**Issue by djskinner** [baconjs/bacon.js#613]
Take a look at the working CodePen here: http://codepen.io/djskinner/pen/JdpwyY

Pressing the balance button generates a new random number. A Property is created that uses holdWhen to restrict balance updates coming through until a stop event is received.

If I was interested in getting the initial state of the stream template, I might `onValue` and then immediately unsubscribe:

```
streamTemplate.onValue(function(initialState) {
      console.log(initialState);
})();
```
However, once I do this the balance Property behaves differently and I no longer receive updates. Why would this seemingly inert change make such a drastic different to the system? Surely the behaviour of the system shouldn't be dependent on whether someone has subscribe and unsubscribed to the streamTemplate at some point in the past?

I think this is potentially a bug in holdWhen.

Is there a better approach to this problem? I am using Buses and pushing rather than plugging it is is an accurate representation of my application but I'm not sure to what extent that has to the issue.

**Comment by djskinner** [comment]
Also asked on StackOverflow:

http://stackoverflow.com/questions/31205107/bacon-js-strange-behaviour-with-holdwhen-and-onvalue

**Comment by raimohanska** [comment]
Indeed seems wrong. I reduced the problem to this pen: http://codepen.io/anon/pen/dodLjN?editors=001

**Comment by raimohanska** [comment]
Failing test case: 9e08a76

**Comment by raimohanska** [comment]
Well, there was a bug and it's fixed in 0.7.67. Thanks for the find!

**Comment by raimohanska** [comment]
In fact this lead me to find and fix a couple of other bugs too, in `scan` and `bufferWithTime` by adding more aggresive automatic testing. We're at 0.7.69 now!

**Comment by djskinner** [comment]
This latest release has solved the issue. Many thanks for Bacon!

**Comment by raimohanska** [comment]
Good to hear that!
