### ISSUE TITLE
DefinitelyTyped Bacon.js

### ISSUE THREAD

**Issue by alexander-matsievsky** [baconjs/bacon.js#618]
Good day!

As a big fan of Bacon, I recently started to cook a [TypeScript definition file](https://github.com/alexander-matsievsky/DefinitelyTyped-baconjs/blob/master/DefinitelyTyped/baconjs/baconjs.d.ts) for the library.

The method was to go through the [API Reference](https://baconjs.github.io/api.html) and extract the typings from there. However, I've encountered a significant problem of differentiating between `Observable`, `EventStream` and `Property`, for example, in [Common methods in EventStreams and Properties](https://baconjs.github.io/api.html#common-methods-in-eventstreams-and-properties), what started as
```ts
interface Observable<A> {
  map<B>(f:(value:A) => B): Observable<B>;
}
```
has turned to
```ts
interface EventStream<A> {
  map<B>(f:(value:A) => B): EventStream<B>;
}

interface Property<A> {
  map<B>(f:(value:A) => B): Property<B>;
}
```

##### What I want to achieve
1. A typesafe definition for Bacon.js (resolving the kind of problems described above);
2. A comprehensive documentation for the library. Primarily for intellisense, but the possibility of JSDoc autogen is attactive as well.

##### What kind of help I'd be grateful to get
I would much appreciate a person with an familiarity with the library helping me figuring out the typings. Also, I think I've messed up some of the JSDoc syntax, would be nice to fix it.

##### The result
After achieving the above-mentioned goals, I'll push the definition to the [official repo](https://github.com/borisyankov/DefinitelyTyped).

**Comment by alexander-matsievsky** [comment]
While going through this [MD](https://github.com/baconjs/bacon.js/blob/master/README.md#api) I've noticed things like
```[`observable.takeUntil(stream)`](#observable-takeuntil "observable.takeUntil(@ : Observable[A], stream : EventStream[B]) : Observable[A]")```
`d.ts` definition would formalize this ad-hoc typing.

**Comment by wolfflow** [comment]
You may have a look at this d.ts https://github.com/bodil/baconts/blob/master/src/bacon.ts.
Might be obsolete, yet still useful.

**Comment by alexander-matsievsky** [comment]
> Might be obsolete, yet still useful.

Thanks for the link.
However, it has the same flaw as mentioned above.
It has
```ts
export interface Observable<T> {
    map<U>(fn: (value: T) => U): EventStream<U>;
}
```
which contradicts [this description](https://baconjs.github.io/api.html#observable-map):
> maps values using given function, returning a new stream/property.

**Comment by phadej** [comment]
The type definition language is a bit ad hoc, but it predates union types in TypeScript. It seems you can get quite close by substituting `[]` to `<>`. Yet in the documentation where functions are spread away from class, the type of `this` should be still visible somewhere.

**Comment by alexander-matsievsky** [comment]
@phadej Yes, I get it. Thanks for the comment.

I think I'll be able to figure out the correct types from API ref and the src.
I'll close the issue after pushing the `d.ts` to DefinitelyTyped repo.

**Comment by phadej** [comment]
It might make sense to change a scripts how `README.md` is generated, shouldn't to difficult to combine them and produce `d.ts`as another artefact. I could do a small experiment ASAP.

**Comment by alexander-matsievsky** [comment]
@phadej That's worth a try, thank you.

**Comment by alexander-matsievsky** [comment]
I'm working on the typings at the moment.
My initial try was to model `Observable` as
```ts
interface Observable<A> {}
```
Soon I realized that I would need an extension to account for `Error`
```ts
interface Observable<E, A> {}
```

My question is **whether there is a library method to transform error types**?
```ts
interface Observable<E, A> {
  transformError<E2>():Observable<E2, A>
}
```
My understanding is that the following is the case with `mapError`
```ts
interface Observable<E, A> {
  mapError<B>(f:(error:E) => B):Observable<E, A|B>;
}
```

**Comment by alexander-matsievsky** [comment]
Type definitions have been pulled to the [DefinitelyTyped repo](https://github.com/borisyankov/DefinitelyTyped/tree/master/baconjs).

Feel free to use, evaluate, improve!

**Comment by fatso83** [comment]
@alexander-matsievsky where did your types go? the repo is gone.

**Comment by alexander-matsievsky** [comment]
@fatso83 Hi! It was moved one level down to [`types` folder](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/baconjs).

https://github.com/DefinitelyTyped/DefinitelyTyped/commit/354cec620daccfa0ad167ba046651fb5fef69e8a

**Comment by fatso83** [comment]
It actually seems like that will be quite superfluous in [the near future](https://github.com/baconjs/bacon.js/tree/typescript) :smile:

**Comment by alexander-matsievsky** [comment]
@fatso83 Nice seeing the library which introduced me to FRP evolving+) IIRC I wrote these definitions for `v0.7.77`.
