### ISSUE TITLE
Maximum call stack exceeded 

### ISSUE THREAD

**Issue by jezaman** [baconjs/bacon.js#619]
Hi,

I'm sorry if this is normal behaviour due to javascript, but is the following case due to a bug or not:

I've build a component-based system based on Bacon, where each component can have IN/OUT ports. These are implemented using Bacon.Bus.

Whenever i create a loop (by connecting a component's OUT port to it's own IN port, i get a 'Uncaught RangeError: Maximum call stack size exceeded' within a second. 

What exactly is going on behind the scenes? Why do i get this error? Each INport is just using bus.onValue(func) where func does a bus.push(data) to the OUTport's bus.

**Comment by pnex2000** [comment]
If I understand you correctly, you're pushing in an onValue handler to the same bus whose handler it is. This will lead to infinite recursion, which begs the question what are you trying to do? A code example may also clarify things a bit.

**Comment by jezaman** [comment]
Consider this example,

Let's say i just want to create a counter that prints on the screen forever, and counts as fast as the system allows.

![GitHub Logo](http://i57.tinypic.com/263a61y.png)

I would do this by creating a loop on the counter component. Intervaltrigger will send 1 signal, counter will process this and keep sending signals to itself, while also to the printer.

Each port you see here is a bus, and i don't want the potential loop to create a 'Uncaught RangeError: Maximum call stack size exceeded', I would expect that it would just keep counting

**Comment by pnex2000** [comment]
There's no tail recursion optimization, so pushing a new event in a handler won't allow the handler to return before the handler is triggered for a new event, causing unbounded stack growth. What to do depends on the case, I suggest to have a look at Bacon.repeat for generating events.

**Comment by philipnilsson** [comment]
What happens if you use a zero-time delay the feedback part (dotted line)?

Also try to include a small code example as something concrete, or we'll have a hard time getting to what you want since (I believe) we have not really defined precise semantics for this type of "fixpoints" of streams.

**Comment by philipnilsson** [comment]
Here's a generic fix-point combinator you can use to make a self-referential counter. The `delay(0)` in the counter will be necessary unfortunately, the story around synchronously occuring events is not good enough to support this.

```
Bacon.fix = f => {
  return new Bacon.EventStream(sink => {
    const bus = new Bacon.Bus();
    return f(bus).subscribe(ev => {
      sink(ev);
      if (ev.isNext()) bus.push(ev.value());
      else if (ev.isEnd()) bus.end();
      else if (ev.isError()) bus.error(ev.error)
    });
  });
};

const counter = Bacon.fix(input => {
  return Bacon.once(1).merge(input.map(x => x + 1)).delay(0);
});

counter.take(10000).log() // successfully prints numbers 1...10000 
```

I'm closing this, I don't see us supporting this to a better extent.
