### ISSUE TITLE
Figuring out join combinators.

### ISSUE THREAD

**Issue by alexander-matsievsky** [baconjs/bacon.js#620]
Good day!

Please take a look at [this](https://github.com/alexander-matsievsky/circuitry.ts/blob/master/examples/todo/classic/js/main.ts#L111-L169). It is an implementation of a reference [TodoMVC app](http://todomvc.com/).

The solution works as advertised. Nevertheless, I feel I'm missing something about joining streams.

###### [`update` function](https://github.com/alexander-matsievsky/circuitry.ts/blob/master/examples/todo/classic/js/main.ts#L119-L152)

At first I though that would work:
```ts
if (error) {
  return new Bacon.Error(error);
} else {
  return new Bacon.Next([todos, todo]);
}
```
 but had to settle for a solution with node-like running state:
```ts
if (error) {
  return [todos, error, null];
} else {
  return [todos, null, todo];
}
```
Is my reasoning flawed?

###### [`when` joins](https://github.com/alexander-matsievsky/circuitry.ts/blob/master/examples/todo/classic/js/main.ts#L155-L169)

The `update` stream holds the the current todo-list `:Todo[]` and the last change with full info `:Todo` (whether creation, update or deletion). This code block extracts this change in a categorized way. My question is whether I'm doing it right or there is a better way to handle a situation like
> `POST` triggered an `update`. Get the events from `update` initiated by `POST` and skip the ones triggered by `PUT` and `DELETE`.

**Comment by alexander-matsievsky** [comment]
@raimohanska Could you help me out with the above issue?

**Comment by raimohanska** [comment]
sorry I'm a bit buy. maybe someone else has time to review the code?

**Comment by alexander-matsievsky** [comment]
@raimohanska Yes, of course. Thanx for an amazing library!+)
