### ISSUE TITLE
cloudfare doesn't update.

### ISSUE THREAD

**Issue by phadej** [baconjs/bacon.js#632]
Latest version there seems to be http://cdnjs.cloudflare.com/ajax/libs/bacon.js/0.7.71/Bacon.min.js

**Comment by wolfflow** [comment]
Not at all, proof below:
https://cdnjs.cloudflare.com/ajax/libs/bacon.js/0.7.76/Bacon.js
https://cdnjs.com/libraries/bacon.js

**Comment by raimohanska** [comment]
So this is ok. Maybe a glitch with Cloudflare?

**Comment by phadej** [comment]
Probably
