### ISSUE TITLE
Running tests separately is broken

### ISSUE THREAD

**Issue by raimohanska** [baconjs/bacon.js#643]
Now that more pieces have now been converted to Javascript, its impossible to test some pieces in separation. Try `./test scan` for example.

The problem is that when running tests that have additional dependencies, the dependency order is invalid and you get

    AssertionError: There shouldn't be coffee pieces after js ones.

**Comment by lautis** [comment]
I'm planning on converting the rest of files to JS as well. The biggest blocker is trying to avoid too bad conflicts with active PRs.

If necessary, tests can be converted as well. Having only one language should simplify the situation.
