### ISSUE TITLE
Link to https://baconjs.github.io/ in the headline

### ISSUE THREAD

**Issue by laurilehmijoki** [baconjs/bacon.js#655]
![image](https://cloud.githubusercontent.com/assets/864166/11610338/c74ad218-9ba8-11e5-8825-92920fc9f1f0.png)

At the moment the headline only contains the text "FRP (functional reactive programming) library for Javascript". Please consider adding a link to https://baconjs.github.io onto that same line – the GitHub UI provides an "Edit" button for the project maintainers. You can use that button to enter the github.io URL.

**Comment by raimohanska** [comment]
Done!
