### ISSUE TITLE
Usage of Array.from in bacon.js

### ISSUE THREAD

**Issue by tonekk** [baconjs/bacon.js#656]
The `bacon.js` file provided in `dist/` (and thus also in npm) makes use of `Array.from` which is not widely supported.

I guess this is something that can be configured during Coffeescript transpilation and it should be, because I was not able to use bacon in Safari 8 (which ships with every Mac Version older than El Capitan).

**Comment by lautis** [comment]
There indeed seems to be a configuration error with the s6 loose mode support. I guess I need to get back working on #651 to prevent this from happening in the future.
