### ISSUE TITLE
fold issues with ES5

### ISSUE THREAD

**Issue by nogo10** [baconjs/bacon.js#669]
As shown on [stackoverflow question](http://stackoverflow.com/questions/38041302/bacon-js-accumulator) 
ES6 arrow function " => " works fine with[ observable.fold(seed, f)](https://github.com/baconjs/bacon.js#observable-fold)
```
const stream = Bacon.sequentially(100, ["Hello", "world"])    
stream.log("stream")
const concatenated = stream.fold("", (a,b) => a + b)
concatenated.log("concatenated")
```

However in strict ES5 syntax:
```
var stream = Bacon.sequentially(100, ["Hello", "world"]);
stream.log("stream");
var concatenated = stream.fold("", function (a,b){ a + b});
```
 it doesn't work results in 'undefined' value on console

**Comment by raimohanska** [comment]
You're missing a `return` statement :)

**Comment by darrennolan** [comment]
Because you've missed a return.

const concatenated = stream.fold("", (a,b) => a + b)

In es5 is actually

var concatenated = stream.fold("", function (a,b){ return a + b});

**Comment by darrennolan** [comment]
Sorry... Slow to the thread.

**Comment by nogo10** [comment]
Ok solved for me ..im the slow one
