### ISSUE TITLE
One issue about the example in baconjs homepage

### ISSUE THREAD

**Issue by PigeonT** [baconjs/bacon.js#680]
how can I write the second example in the homepage of baconJS like this? I've no idea how to write here the 'flatMap' function so that I can always chaining the whole things?
![baconjs](https://cloud.githubusercontent.com/assets/9105977/21424180/51f1cfaa-c841-11e6-9ddb-febdbd8d7400.png)

**Comment by darrennolan** [comment]
Keep chaining away.  Should probably be something like the following (you only ever really one want `subscriber`, or one `onValue` call.

```
const URL = 'https://myUrl.com';

$('#movieSearch').asEventStream('keyup')
  .debounce(300)
  .skipDuplicates()
  .flatMap(c => {
      return Bacon.fromPromise($.get(URL + c));
  })
  .onValue(c => console.log(c));
```

**Comment by raimohanska** [comment]
Well put, @darrennolan. 

The fromPromise+$.get combo should work quite well too. Or you can just use the [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) instead of jQuery AJAX as well. The fetch function returns a Promise that you can wrap with `Bacon.fromPromise`.

**Comment by PigeonT** [comment]
thx a lot, very clever solution. What I was confused about is actually the argument in the function passed into flatmap. E.g. I've flatMap((x) => {What means x here actually?}), I searched a lot as well as in docs, but no one explained that.

**Comment by raimohanska** [comment]
The `x` in the function passed to `flatMap` will be the value from the source stream. Actually in @darrennolan's example it will be the the keyup event, while it should be the current value of the text field. So, I'd modify the example to contain the `.map(".target.value")` part that was included in the original example.

**Comment by raimohanska** [comment]
If you're familiar with Promises, `flatMap` does the same thing as `Promise.then` (except it doesn't force a subscription on the stream).
