### ISSUE TITLE
Error: Permission denied to access property "_isEvent"

### ISSUE THREAD

**Issue by Gekkio** [baconjs/bacon.js#685]
We're seeing this error sometimes on Firefox 51, Windows and OS X. It might be caused by some addon or privacy mode.

```
Error: Permission denied to access property "_isEvent"
  File "webpack:///./~/baconjs/dist/Bacon.js" line 949 col 1 in ct
    if (x && x._isEvent) {
  File "webpack:///./~/baconjs/dist/Bacon.js" line 1719 col 1 in O.fromBinder/</a<
    reply = sink(event = toEvent(event));
```

bacon.js v0.7.89

**Comment by raimohanska** [comment]
Still seeing this?

**Comment by Gekkio** [comment]
Yeah, still happening sometimes. Firefox 48+ and Windows/macOS/Linux/Android, but it's relatively rare so it's clearly caused by some configuration or addon.
