### ISSUE TITLE
Problems after Update

### ISSUE THREAD

**Issue by Phoscur** [baconjs/bacon.js#693]
```javascript
function containsObs(obs, aftersList) {
    for (var i in aftersList) {
>      if (aftersList[i][0].id == obs.id) return true;
    }
    return false;
  }
```
It throws with 
```
   TypeError: Cannot read property 'id' of undefined at containsObs (main.generated.js:15853)
    at afterTransaction (main.generated.js:15836)
    at Object.sink (main.generated.js:15978)
    at PropertyDispatcher.Dispatcher.pushToSubscriptions (main.generated.js:16740)
    at PropertyDispatcher.Dispatcher.pushIt (main.generated.js:16762)
    at Object.inTransaction (main.generated.js:15947)
    at PropertyDispatcher.Dispatcher.push (main.generated.js:16731)
    at PropertyDispatcher.push (main.generated.js:17172)
    at PropertyDispatcher.Dispatcher.handleEvent
```
Trace ends there.
I've come so far, that I can say that there is a function in the aftersList, that doesn't have an id.

How to fix this? Gotta roll back to older Bacon for now.
Rollback to 0.7.59 solves the issues (it' the only version I'm trying now though)

**Comment by raimohanska** [comment]
Interesting and yet unseen. Any chance of producing an isolated repeatable scenario in webpackbin, jsfiddle or such?

**Comment by Phoscur** [comment]
I cannot isolate this as I don't know exactly what actually triggers it. The trace is too short. Sadly bacon Code is often difficult to debug. 
Can you find out anything reviewing Code and changes?

**Comment by raimohanska** [comment]
I understand. I'll take a look at this soon.

**Comment by Phoscur** [comment]
These Bacon statements should be relevant for the problem - not sure though.
```javascript
      function deviceStream(id) {
        return Bacon.fromPromise(getDevice(id).catch(restoreOffline));
      }

      deviceBus = new Bacon.Bus();
      deviceProperty = deviceBus.toProperty();


      deviceProperty.init = function() {
        if (!store.get('deviceID')) { // first device initialization
          // expose the creating promise instance
          // so other domain entity busses can await it
          deviceProperty.creating = newDevice().then(function(device) {
            deviceBus.push(device);
            return device;
          });
        } else {
          deviceBus.plug(deviceStream(store.get('deviceID')));
        }
        return deviceBus;
      };
```

**Comment by raimohanska** [comment]
I added a couple of extra assertions and an console.error message to debug this. Haven't figured out how this happens yet. If you care to try with [this build](https://github.com/baconjs/bacon.js/tree/03827919867e3f29c0efe67c5669e82b92d5dd35/dist) it might help to sort this out.

**Comment by raimohanska** [comment]
So far I haven't figured out a way how an entry [obs, f] with obs==null or an empty entry [] could be in the aftersStack, unless an undefined observable is pushed into the stack. But that should also be impossible. If you run your app with the bacon.js build linked above and report errors here, it might help us to have a clue. Just replace the `Bacon.js` file with the linked one under your `node_modules/baconjs/dist` directory and repeat the problem.

**Comment by raimohanska** [comment]
When running, make sure you see the message "Debugging issue #693" in your console, to make sure you're actually running with this special build :)

**Comment by raimohanska** [comment]
Mighst also make sense to try with Bacon.js version 0.7.92 to narrow down the problem to the new "after transaction processing logic" introduced in 0.7.93. I'll do my best to fix this, but currently can't think of a way to reproduce the problem.

Another pair of eyes and a brain might help :) It seems that the state in the `aftersStack` variable in [updatebarrier.js](https://github.com/baconjs/bacon.js/blob/master/src/updatebarrier.js) gets somehow corrupted. Also, maybe it's time to move to TypeScript?

**Comment by raimohanska** [comment]
Oh, an even easier way to test the application with this special build is by modifying your `package.json` to contain

```
  "dependencies": {
    "baconjs": "baconjs/bacon.js#693"
  }
```

This will get you the branch "693" from Github.

**Comment by Phoscur** [comment]
```require.js:900 l {error: "observable missing from at index remove in array B…(){if(!n){var e=t(r);if(e===w.noMore)return o()}}", id: 24}
error: "observable missing from at index remove in array Bacon.Bus().toProperty(true).take(1),function (){if(!n){var e=t(r);if(e===w.noMore)return o()}}"id: 
```

![image](https://user-images.githubusercontent.com/191093/27263464-c2a1257a-5469-11e7-9749-37cc1066b40f.png)

**Comment by Phoscur** [comment]
Sorry again with better traces:
![image](https://user-images.githubusercontent.com/191093/27263807-beb1aa04-5471-11e7-91d8-e3353246ae02.png)

**Comment by Phoscur** [comment]
```javascript
// internal-domain.js:29
return isOnlineBus.toProperty(ionic.Platform.isWebView() ? $cordovaNetwork.isOnline() : navigator.onLine).log('isOnline');
```
Problems with this Boolean Bus?

**Comment by raimohanska** [comment]
Well it surely looks like there's an Observable where there's supposed to be an array (the aftersList appears to be an Observable).

**Comment by raimohanska** [comment]
hmm.. in fact I think this is the classic problem with the `for (var i in array)`: when there are additional methods added to the Array prototype, they'll appear as indices in the for-loop. Patch coming up!

**Comment by raimohanska** [comment]
We had added junk into the Array prototype in Bacon.js tests but unfortunately our "junk" was a string so it didn't make tests fail. I added more junk (functions, objects, null ...) to the prototype and was able to reproduce this bug. The fix was simple. Will be included in 0.7.94 as soon as possible.

**Comment by raimohanska** [comment]
..and it's out. Pls test with Bacon.js 0.7.94 and report if it works for you!

Sorry for the inconvenience and thanks a lot for your help! With the improved prototype junk in the tests, there will be no more errors of this kind in future releases.

**Comment by Phoscur** [comment]
Okay nice :) 
Question: why only minor version bumps with The latest reworks and additions?

**Comment by raimohanska** [comment]
That's a fair question! I think we should stop this madness and promote the current version as 1.0. Then do semantic versioning.

**Comment by raimohanska** [comment]
See #694 :)

**Comment by Phoscur** [comment]
Indeed fixed in the latest release! Good job!
