### ISSUE TITLE
Transactions question

### ISSUE THREAD

**Issue by andpor** [baconjs/bacon.js#695]
There is a concept of transactions in mobx which works quite well especially when several updates are performed within it. Is there a concept of transaction in Baconjs whereby even though two or more properties are updated within a transaction, their subscribers are not notified until the end of that transaction?

**Comment by raimohanska** [comment]
There's [Atomic updates](https://github.com/baconjs/bacon.js/#atomic-updates) which is there to remove glitches in case of a "diamond-shaped" or more complex event network. The documentation doesn't mention transactions as such, but internally there's a transaction that spans the processing of a single incoming event. The external subscribers aren't called until all of the updates in the transaction have been fully processed.

Is this what your looking for or do you need a way to programmatically control your transaction boundaries?

**Comment by andpor** [comment]
yeah, I was looking for more programmatic transaction boundary control...

**Comment by raimohanska** [comment]
Ok then! There's no such thing as such. Of course there are probably several ways of "holding back" events until a later time. For instance, there's [`holdWhen`](https://baconjs.github.io/api.html#stream-holdwhen)  and acts like a valve. This is easy if there's a single point (observable) where you can apply your "valve".

**Comment by raimohanska** [comment]
Another way could be [`sampledBy`](https://baconjs.github.io/api.html#property-sampledby) that you can use to sample the status of a Property at a given time.
