### ISSUE TITLE
debounce swallows initial value?

### ISSUE THREAD

**Issue by pvakevai** [baconjs/bacon.js#736]
With bacon v2.0.11

Bacon.mergeAll(Bacon.Bus().toProperty('')).toProperty().doLog('1').debounce(500).log('2')

Does not produce output that I would expect. (both 1 and 2)

**Comment by raimohanska** [comment]
Thanks! I'll investigate this. Looks like a bug related to the "all eventstreams are now asynchronous" change in 2.0.

**Comment by semmel** [comment]
@pvakevai 
Have you looked at [debounceImmediate](http://baconjs.github.io/api3/classes/eventstream.html#debounce)?

Looking at the marble diagram of `debounce` it is ok for it to swallow a lot of events.
<pre>
source:             asdf----asdf----
source.debounce(2): -----f-------f--
</pre>

**Comment by raimohanska** [comment]
I found the bug. It's simple. Just a sec...

**Comment by raimohanska** [comment]
The bug is not related to debounce and friends. It's `mergeAll` instead, passing Initial events into an EventStream, that should never happen.

Fixed in 3.0.1 and 2.0.12.

**Comment by raimohanska** [comment]
Closing now. Please re-open if the fix doesn't help.
