### ISSUE TITLE
Examples at baconjs.github.io are not working

### ISSUE THREAD

**Issue by kosich** [baconjs/bacon.js#746]
"Simple counter" and "Movie search" examples at the root page of [baconjs.github.io](baconjs.github.io) are not working at the moment.

Probably errors in the console would explain why:

![https://i.stack.imgur.com/puvZN.png](https://i.stack.imgur.com/puvZN.png)

**Running**
Google Chrome
Version 76.0.3809.100 (Official Build) (64-bit)
on MacOS

**P.S.** thanks for the great library!

**Comment by raimohanska** [comment]
Thanks for pointing this out! I'll have a look.

**Comment by raimohanska** [comment]
Ha! Seems that the minified version of Bacon.js 3 is totally broken and the file consists of the following string: `undefined`.

**Comment by raimohanska** [comment]
Now it's 80% fixed: the file contains [object Object]!

**Comment by raimohanska** [comment]
Such a javascripty way to fail. Fixed the issue and including in 3.0.10. I guess no-one uses the minified js for reals though.

**Comment by raimohanska** [comment]
Updated the examples too, as they used some shortcuts that were removed in 3.0.

**Comment by kosich** [comment]
That was fast!
Examples are important for novices like me :)

Thanks!
