### ISSUE TITLE
Provide Aggregated ES Module?

### ISSUE THREAD

**Issue by semmel** [baconjs/bacon.js#748]
While it's easy to "import" `dist/Bacon.js` in a web page using an AMD loader or simply via `<script>` tag, there is no distribution file for importing as ES module:
`import * as Bacon from "../dist/.Bacon.mjs"` requires transpiling and bundling from the *original sources* - `npm install baconjs` is insufficient.
Could such an aggregated ES module file not be generated in `scripts/assemble.js` by rollup?
```javascript
import typescriptPlugin from 'rollup-plugin-typescript2';

const
  config = {
    input: './src/bacon.ts',
    output: {
      format: "esm",
      file: "./dist/Bacon.mjs"  // <-- or whatever name
    },
    plugins:[
      typescriptPlugin({
        typescript: require("typescript"),
        useTsconfigDeclarationDir: true
      })
    ]
  };
  export default config;
```

It would certainly help with "build-step free" development in the browser.

**Comment by raimohanska** [comment]
Sure, that would be great! Would you like to submit a related Pull Request :)
