### ISSUE TITLE
doLog on Bus

### ISSUE THREAD

**Issue by bonthronResearch** [baconjs/bacon.js#762]
It doesn't appear doLog is working on Buses.

**Comment by raimohanska** [comment]
And how did you come to this conclusion? Please provide an example!

**Comment by raimohanska** [comment]
Here's a demonstration how it works: https://codesandbox.io/s/baconjs-dolog-1vejp?file=/src/index.js

**Comment by bonthronResearch** [comment]
Thanks so much! I miss understood how to use it. (I love Bacon BTW..)

**Comment by raimohanska** [comment]
No problem! Have a great day!
