### ISSUE TITLE
examples are not working

### ISSUE THREAD

**Issue by jutunen** [baconjs/bacon.js#769]
When trying out examples from https://rawgit.com/baconjs/bacon.js/master/examples/examples.html

I get following error to console:

![Screenshot at 2020-08-20 12-49-29](https://user-images.githubusercontent.com/5544638/90755550-e83d3380-e2e3-11ea-92c1-3960883e5054.png)

**Comment by raimohanska** [comment]
Oh I had totally forgotten these examples exist. Let's see...

**Comment by raimohanska** [comment]
Fixed! I removed jQuery from there.

This has been broken for the longest time. Nowadays, to use Bacon with jQuery you need to do this: https://github.com/baconjs/bacon.js#for-jquery-users

**Comment by jutunen** [comment]
Ok, it seems to work now, thank you!
