### ISSUE TITLE
examples.html is not working - ReferenceError: Bacon is not defined

### ISSUE THREAD

**Issue by milahu** [baconjs/bacon.js#804]
https://github.com/baconjs/bacon.js/blob/c5a1bfdd56cfcb1de6f4bd26c02c34223f41a1c2/examples/examples.html#L3

http://htmlpreview.github.io/?https://rawgit.com/baconjs/bacon.js/master/examples/examples.html

Uncaught ReferenceError: Bacon is not defined

but https://baconjs.github.io/ has some examples

**Comment by raimohanska** [comment]
Well the pages you refer to are not made to work when viewed through htmlpreview.github.io. You can clone the Bacon.js repository and view them on your own machine. The baconjs.github.io site seems to work fine.
