### ISSUE TITLE
Errors not captured in methods?

### ISSUE THREAD

**Issue by jaidetree** [baconjs/bacon.js#809]
Given code like the following:

```js
Bacon
 .once(null)
 .map((_x) => {
   throw new Error("Expected failure")
 }) 
 .toPromise()
 .then(x => {
  console.log("Promise was unexpectedly resolved")
 })
 .catch(x => {
   if (x instanceof Error && x.message.includes("Expected failure")) {
     console.log("Handled the expected failure")
   } else {
     console.log("Something went wrong")
   }
 })
```

I expect the error in the map operator to make its way through the promise, then the catch handler can test the error and log my expected message.

Instead, the stream exits immediately and it seems like an error is thrown outside of the stream.

Is the idea that I should be wrapping my logic in a try...catch clause or is this an unexpected bug?

**Comment by raimohanska** [comment]
It’s intended - Bacon has never caught exceptions. The thinking is that exceptions are treated as programming errors and should fail fast. Which is ofc opinionated.

**Comment by jaidetree** [comment]
Thanks for the insight, seems reasonable

**Comment by semmel** [comment]
@jaidetree Otherwise you can use [`Bacon.try`](https://github.com/baconjs/bacon.js/blob/f737f52382ecba20cae2d1d4e423af23830dc1de/README.md#errors) together with `.flatMap` like this:

`wrapped = source.flatMap(Bacon.try(dangerousOperation))`

**Comment by jaidetree** [comment]
That's perfect thanks!
