### ISSUE TITLE
Bacon.try missing in docs

### ISSUE THREAD

**Issue by jaidetree** [baconjs/bacon.js#810]
Thanks to @semmel in https://github.com/baconjs/bacon.js/issues/809#issuecomment-2198563774 for mentioning Bacon.try. However, looking at the readme errors section it links to http://baconjs.github.io/api3/globals.html#try which is not surfaced anywhere.

I'm down for creating a PR to fix this, but need some guidance on how you'd like me to fix this. My thinking is it'd be worth exposing in the api v3 docs but alternatively, the link could be removed from the readme.

**Comment by raimohanska** [comment]
It's now in the docs as per version 3.0.19. The function is named `tryF` because `try` is a reserved word. The documentation hopefully makes it's usage clear enough though.

**Comment by jaidetree** [comment]
Thanks for updating it!
